// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aznicvibeopcuszivpcx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bmljdmliZW9wY3Vzeml2cGN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY1NTI4MzUsImV4cCI6MjA2MjEyODgzNX0.jOkII1QjHon3n0Z7XbwhTbCkgMYdM3QonpMdMcylK-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);